name: syn_repo_dev
on: 
  workflow_call:


jobs:
  run_dbt:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/dbt-labs/dbt-core:1.9.3
    steps:
      #checkout the repo
      - uses: actions/checkout@v4

      #install dbt
      - name: dbt and edr installation
        run: |
          python -m pip install dbt-duckdb
          cd ./jaffle_shop
          dbt run --target dev
